# Talmi EEG Data Preparation

Prepare the Talmi EEG study events for RecallDataset ingestion while tracking data quality decisions.

## Preprocessing Decisions
- Use the behavioral CSV to supply the full 20 study events for every subject/list before merging EEG features.
- Derive presentation order as TrialNumber - 2 and drop EEG rows with PresentationOrder == 99 whenever the trial already has 20 observations.
- Map rater codes so (1,1)→1.0, (2,2)→0.0, and (3,2)→0.5; store a lenient recalls array (0.5→recalled) and a strict ambiguous_recalls array (0.5→not recalled), both sorted by study position with trailing zeros.
- Preserve recorded item identities; otherwise generate deterministic placeholders and flag them in imputed_mask.
- Factorize study-level columns with fixed codes (ImgName via pd.factorize; Condition Negative→1, Neutral→2; ThreeConds Negative→1, Neutral→2, Category→3).
- Impute missing Early/Late LPP values using within-list, within-condition means, falling back to list means and then global condition means; mark those cells in lpp_imputed.
- Omit TrialNumber in the final dataset but retain subject, list (as column vectors), and listLength to satisfy the RecallDataset schema.
- Export per-position arrays (EarlyLPP, LateLPP, condition, cond3, imputed_mask, lpp_imputed, ambiguous_recalls) alongside the standard RecallDataset fields, accepting float types where needed.
- Confirm every participant contributes the modal nine lists so downstream code can rely on consistent trial counts.

## Setup

In [1]:
#| code-summary: Import modules for Talmi EEG profiling
import numpy as np
import pandas as pd
from pathlib import Path

from jaxcmr.helpers import save_dict_to_hdf5, find_project_root, generate_trial_mask

In [2]:
#| code-summary: Load behavioral and EEG CSV resources
DATA_DIR = Path('data/raw/talmieeg')
EEG_PATH = DATA_DIR / 'Single_Trial_Behavioural_and_EEG_Data_Z.csv'
BEHAVIOR_PATH = DATA_DIR / 'All_Included_Subjects.csv'

eeg_df = pd.read_csv(EEG_PATH)
behavior_df_raw = pd.read_csv(
    BEHAVIOR_PATH,
    header=None,
    names=[
        'Participant',
        'List',
        'TrialNumber',
        'ThreeCondsCode',
        'ConditionCode',
        'ThreeConds',
        'Recalled',
    ],
)

In [3]:
eeg_df.head()

,Participant,List,3Conds,Condition,TrialNumber,PresentationOrder,ImgName,Recalled,EarlyLPP,LateLPP
0,202,1,Negative,Negative,3,1,neg139,1,-3.95610,-1.84030
1,202,1,Neutral,Neutral,4,2,neut2,1,0.66242,-0.23096
2,202,1,Negative,Negative,5,3,neg138,1,-0.56351,-0.30037
3,202,1,Negative,Negative,6,4,neg132,0,0.72071,0.91095
4,202,1,Category,Neutral,7,5,cat124,0,-0.64235,0.51120

In [4]:
behavior_df_raw.head()

,Participant,List,TrialNumber,ThreeCondsCode,ConditionCode,ThreeConds,Recalled
0,202,1,3,1,1,Negative,1
1,202,1,4,2,2,Neutral,1
2,202,1,5,1,1,Negative,1
3,202,1,6,1,1,Negative,0
4,202,1,7,3,2,Category,0

## Helper Functions

In [5]:
#| code-summary: Define helpers for order alignment and imputation

TARGET_LIST_LENGTH = 20

def factorize_series(values: pd.Series, *, categories: list[str] | None = None) -> tuple[pd.Series, list[str]]:
    """Returns 1-based factor codes for provided series.

    Args:
      values: Column to convert into categorical codes.
      categories: Explicit category order assigning 1-based codes.

    Returns:
      Tuple of the 1-based codes aligned with the input index and the category labels.
    """
    if categories is None:
        codes, derived = pd.factorize(values, sort=True)
        return pd.Series(codes + 1, index=values.index), list(derived)
    mapping = {label: index + 1 for index, label in enumerate(categories)}
    mapped = values.map(mapping)
    if mapped.isna().any():
        unknown = values[mapped.isna()].unique().tolist()
        raise ValueError(f"Encountered unexpected categories: {unknown!r}")
    return mapped.astype(int), categories

def prepare_behavioral_dataframe(path: Path) -> pd.DataFrame:
    """Returns behavioral events with presentation order and recall flags.

    Args:
      path: Location of the behavioral CSV without headers.
    """
    df = pd.read_csv(
        path,
        header=None,
        names=[
            'Participant',
            'List',
            'TrialNumber',
            'ThreeCondsCode',
            'ConditionCode',
            'ThreeConds',
            'Recalled',
        ],
    )
    df['PresentationOrder'] = df['TrialNumber'] - 2
    df = df[df['PresentationOrder'].between(1, TARGET_LIST_LENGTH)].copy()
    df['Condition'] = df['ConditionCode'].map({1: 'Negative', 2: 'Neutral'})
    df['Recalled'] = df['Recalled'].astype(int)
    return df

def merge_behavior_and_eeg(behavior_df: pd.DataFrame, eeg_df: pd.DataFrame) -> pd.DataFrame:
    """Merge behavioral events with EEG features on presentation order.

    Args:
      behavior_df: Prepared behavioral rows with presentation order and recall flags.
      eeg_df: EEG rows including `ImgName`, `EarlyLPP`, and `LateLPP`.
    """
    usable_eeg = eeg_df[eeg_df['PresentationOrder'].between(1, TARGET_LIST_LENGTH)]
    return behavior_df.merge(
        usable_eeg[[
            'Participant',
            'List',
            'PresentationOrder',
            'ImgName',
            'EarlyLPP',
            'LateLPP',
        ]],
        on=['Participant', 'List', 'PresentationOrder'],
        how='left',
    )

def assign_img_placeholders(merged_df: pd.DataFrame) -> pd.DataFrame:
    """Fill missing image names with deterministic placeholders.

    Args:
      merged_df: Rows after aligning behavior and EEG tables.
    """
    df = merged_df.copy()
    missing_mask = df['ImgName'].isna()
    df.loc[missing_mask, 'ImgName'] = df.loc[missing_mask].apply(
        lambda row: f"missing_{int(row.Participant)}_{int(row.List)}_{int(row.PresentationOrder)}",
        axis=1,
    )
    df['imputed_mask'] = missing_mask.astype(int)
    return df

def impute_lpp_by_condition(df: pd.DataFrame) -> pd.DataFrame:
    """Impute missing LPP values using within-list condition averages.

    Args:
      df: Aligned study events containing LPP columns and condition labels.
    """
    result = df.copy()
    initial_missing = result[['EarlyLPP', 'LateLPP']].isna().any(axis=1)
    cond_means = result.groupby(['Participant', 'List', 'Condition'])[['EarlyLPP', 'LateLPP']].transform('mean')
    list_means = result.groupby(['Participant', 'List'])[['EarlyLPP', 'LateLPP']].transform('mean')
    global_means = result.groupby('Condition')[['EarlyLPP', 'LateLPP']].mean()
    for column in ['EarlyLPP', 'LateLPP']:
        result[column] = result[column].fillna(cond_means[column])
        result[column] = result[column].fillna(list_means[column])
        result[column] = result[column].fillna(result['Condition'].map(global_means[column]))
        result[column] = result[column].fillna(0.0)
    result['lpp_imputed'] = (
        initial_missing | result[['EarlyLPP', 'LateLPP']].isna().any(axis=1)
    ).astype(int)
    return result

def build_recall_dataset(completed_df: pd.DataFrame) -> dict[str, np.ndarray]:
    """Returns RecallDataset-aligned arrays including recall tracks.

    Args:
      completed_df: Study events with factorized identifiers and imputation flags.
    """
    ordered = completed_df.sort_values(['Participant', 'List', 'PresentationOrder'])
    trial_groups = list(ordered.groupby(['Participant', 'List'], sort=True))
    trial_count = len(trial_groups)
    subject = np.zeros((trial_count, 1), dtype=int)
    list_ids = np.zeros((trial_count, 1), dtype=int)
    list_length = np.full((trial_count, 1), TARGET_LIST_LENGTH, dtype=int)
    pres_itemnos = np.tile(np.arange(1, TARGET_LIST_LENGTH + 1, dtype=int), (trial_count, 1))
    pres_itemids = np.zeros((trial_count, TARGET_LIST_LENGTH), dtype=int)
    early_lpp = np.zeros((trial_count, TARGET_LIST_LENGTH), dtype=float)
    late_lpp = np.zeros((trial_count, TARGET_LIST_LENGTH), dtype=float)
    condition = np.zeros((trial_count, TARGET_LIST_LENGTH), dtype=int)
    cond3 = np.zeros((trial_count, TARGET_LIST_LENGTH), dtype=int)
    imputed_mask = np.zeros((trial_count, TARGET_LIST_LENGTH), dtype=int)
    lpp_mask = np.zeros((trial_count, TARGET_LIST_LENGTH), dtype=int)
    recalls = np.zeros((trial_count, TARGET_LIST_LENGTH), dtype=int)
    restricted_recalls = np.zeros((trial_count, TARGET_LIST_LENGTH), dtype=int)
    rec_itemids = np.zeros((trial_count, TARGET_LIST_LENGTH), dtype=int)
    for trial_index, ((participant, list_id), block) in enumerate(trial_groups):
        block = block.sort_values('PresentationOrder').reset_index(drop=True)
        subject[trial_index, 0] = int(participant)
        list_ids[trial_index, 0] = int(list_id)
        pres_itemids[trial_index, :] = block['item_id_code'].to_numpy(dtype=int)
        early_lpp[trial_index, :] = block['EarlyLPP'].to_numpy(dtype=float)
        late_lpp[trial_index, :] = block['LateLPP'].to_numpy(dtype=float)
        condition[trial_index, :] = block['condition'].to_numpy(dtype=int)
        cond3[trial_index, :] = block['cond3'].to_numpy(dtype=int)
        imputed_mask[trial_index, :] = block['imputed_mask'].to_numpy(dtype=int)
        lpp_mask[trial_index, :] = block['lpp_imputed'].to_numpy(dtype=int)
        recalled_positions = block.loc[block['Recalled'] == 1, 'PresentationOrder'].astype(int).tolist()
        recalled_item_ids = block.loc[block['Recalled'] == 1, 'item_id_code'].astype(int).tolist()
        for recall_index, position in enumerate(recalled_positions):
            recalls[trial_index, recall_index] = position
            restricted_recalls[trial_index, recall_index] = position
            rec_itemids[trial_index, recall_index] = recalled_item_ids[recall_index]
    return {
        'subject': subject,
        'list': list_ids,
        'listLength': list_length,
        'pres_itemnos': pres_itemnos,
        'pres_itemids': pres_itemids,
        'recalls': recalls,
        'restricted_recalls': restricted_recalls,
        'rec_itemids': rec_itemids,
        'EarlyLPP': early_lpp,
        'LateLPP': late_lpp,
        'condition': condition,
        'cond3': cond3,
        'lpp_imputed': lpp_mask,
    }

## Diagnostics

In [6]:
#| code-summary: Identify EEG rows flagged with presentation order ninety-nine
presentation_order_99 = (
    eeg_df[eeg_df['PresentationOrder'] == 99]
    .groupby(['Participant', 'List'])
    .size()
    .reset_index(name='count_presentationorder_99')
    .sort_values(['Participant', 'List'])
)
presentation_order_99

    Participant  List  count_presentationorder_99
0           202     7                           1
1           203     7                           1
2           204     7                           1
3           205     7                           1
4           206     7                           1
5           207     7                           1
6           210     7                           1
7           211     7                           1
8           212     7                           1
9           213     7                           1
10          214     7                           1
11          215     7                           1
12          216     7                           1
13          217     7                           1
14          218     7                           1
15          219     7                           1
16          220     7                           1
17          220     9                           1
18          221     7                           1
19          222     7                           1
20          223     7                           1
21          224     7                           1
22          225     7                           1
23          226     7                           1
24          227     7                           1
25          229     7                           1
26          230     7                           1
27          231     7                           1
28          232     7                           1
29          233     7                           1
30          234     7                           1
31          235     7                           1
32          237     7                           1
33          238     7                           1
34          239     1                           2
35          239     7                           1
36          240     7                           1
37          242     7                           1

In [7]:
#| code-summary: Prepare behavioral dataframe for diagnostics
behavior_df = prepare_behavioral_dataframe(BEHAVIOR_PATH)
merged_preview = merge_behavior_and_eeg(behavior_df, eeg_df)
behavior_df.head()

,Participant,List,TrialNumber,ThreeCondsCode,ConditionCode,ThreeConds,Recalled,PresentationOrder,Condition
0,202,1,3,1,1,Negative,1,1,Negative
1,202,1,4,2,2,Neutral,1,2,Neutral
2,202,1,5,1,1,Negative,1,3,Negative
3,202,1,6,1,1,Negative,0,4,Negative
4,202,1,7,3,2,Category,0,5,Neutral

In [8]:
#| code-summary: Summarize recall distribution
behavior_df['Recalled'].value_counts().to_dict()

{0: 3766, 1: 3074}

In [9]:
#| code-summary: Compare recalled events with and without EEG measurements
recalled_mask = behavior_df['Recalled'] == 1
lpp_missing_mask = merged_preview[['EarlyLPP', 'LateLPP']].isna().any(axis=1)

lpp_presence_summary = {
    'recalled_total': int(recalled_mask.sum()),
    'recalled_without_eeg': int((recalled_mask & lpp_missing_mask).sum()),
    'recalled_with_eeg': int((recalled_mask & ~lpp_missing_mask).sum()),
    'not_recalled_without_eeg': int((~recalled_mask & lpp_missing_mask).sum()),
    'not_recalled_with_eeg': int((~recalled_mask & ~lpp_missing_mask).sum()),
}
lpp_presence_summary

{'recalled_total': 3074,
 'recalled_without_eeg': 140,
 'recalled_with_eeg': 2934,
 'not_recalled_without_eeg': 231,
 'not_recalled_with_eeg': 3534}

In [10]:
#| code-summary: Recall rate by condition
behavior_df.groupby('Condition')['Recalled'].mean().to_dict()

{'Negative': 0.5322153574580759, 'Neutral': 0.40839527765631833}

## Dataset Preparation

In [11]:
#| code-summary: Factorize identifiers and impute LPP values
aligned_df = assign_img_placeholders(merged_preview)
aligned_df['item_id_code'], item_categories = factorize_series(aligned_df['ImgName'])
aligned_df['item_id_code'] = aligned_df['item_id_code'].astype(int)
aligned_df['condition'], condition_categories = factorize_series(
    aligned_df['Condition'], categories=['Negative', 'Neutral']
)
aligned_df['cond3'], cond3_categories = factorize_series(
    aligned_df['ThreeConds'], categories=['Negative', 'Neutral', 'Category']
)
aligned_df['condition'] = aligned_df['condition'].astype(int)
aligned_df['cond3'] = aligned_df['cond3'].astype(int)
imputed_df = impute_lpp_by_condition(aligned_df)
imputed_df.head()

,Participant,List,TrialNumber,ThreeCondsCode,ConditionCode,ThreeConds,Recalled,PresentationOrder,Condition,ImgName,EarlyLPP,LateLPP,imputed_mask,item_id_code,condition,cond3,lpp_imputed
0,202,1,3,1,1,Negative,1,1,Negative,neg139,-3.95610,-1.84030,0,465,1,1,0
1,202,1,4,2,2,Neutral,1,2,Neutral,neut2,0.66242,-0.23096,0,514,2,2,0
2,202,1,5,1,1,Negative,1,3,Negative,neg138,-0.56351,-0.30037,0,464,1,1,0
3,202,1,6,1,1,Negative,0,4,Negative,neg132,0.72071,0.91095,0,461,1,1,0
4,202,1,7,3,2,Category,0,5,Neutral,cat124,-0.64235,0.51120,0,18,2,3,0

In [12]:
#| code-summary: Assemble RecallDataset arrays and metadata summary
talmi_dataset = build_recall_dataset(imputed_df)
talmi_metadata = {
    'item_categories': item_categories,
    'condition_categories': condition_categories,
    'cond3_categories': cond3_categories,
}
trial_count = int(talmi_dataset['subject'].shape[0])
list_length = int(talmi_dataset['listLength'][0, 0])
recall_density = float(np.count_nonzero(talmi_dataset['recalls']) / talmi_dataset['recalls'].size)
restricted_recall_density = float(
    np.count_nonzero(talmi_dataset['restricted_recalls']) / talmi_dataset['restricted_recalls'].size
)
dataset_summary = {
    'trial_count': trial_count,
    'list_length': list_length,
    'recalls_shape': talmi_dataset['recalls'].shape,
    'recall_density': recall_density,
    'restricted_recall_density': restricted_recall_density,
    'lpp_imputed_items': int(talmi_dataset['lpp_imputed'].sum()),
}
save_dict_to_hdf5(talmi_dataset, f'{find_project_root()}/data/TalmiEEG.h5')
dataset_summary

{'trial_count': 342,
 'list_length': 20,
 'recalls_shape': (342, 20),
 'recall_density': 0.44941520467836255,
 'restricted_recall_density': 0.44941520467836255,
 'lpp_imputed_items': 371}

In [13]:
#| code-summary: (deprecated duplicate cleared)

In [14]:
talmi_dataset['lpp_imputed'].size

6840

In [15]:
subject_mask = generate_trial_mask(talmi_dataset, "data['subject'] == 202")
for key, value in talmi_dataset.items():
    print(f"{key}\n{value[subject_mask]}\n")

subject
[[202]
 [202]
 [202]
 [202]
 [202]
 [202]
 [202]
 [202]
 [202]]

list
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

listLength
[[20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]
 [20]]

pres_itemnos
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]

pres_itemids
[[465 514 464 461  18  22  19 459 505   1  67  25 463  20 515 462 466  21
  513 460]
 [ 44 439 441 475 506   4  10 512 443 442 510 519  68 509   7   9 516   8
   12 438]
 [ 61  69  70 560 556 559  52 491  65 490 473 565 550  28 492 494  62 545
  489   3]
 [500  54 562 503  71 548  72  50  64 563 499 502  60  63 498 569 567 564
  497  55]
 [  5  42 446 528 507 540 520  26  73 448 530 529 444 451 447   2  23 450
  526  11]
 [ 48  46  29 488 480  31 533  38 471 521 535  74 472  75 532 469 468 539
  538 522]
 [ 76 546 527  33 523  40 486 525  13 482 456 487  17 483 524 543 484  15
   16  30]
 [477 478  78 552 474  59  79  80 547 558 470 479  56  36 561 453 549  77
   57 481]
 [ 41 501 457 531 476 536 504  84 534 537  81  43 495 541 455 454  82  83
   32  37]]

recalls
[[ 1  2  3  8 11 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  2  3  4  5 10 11 13 15 17 18 19 20  0  0  0  0  0  0  0]
 [ 4  6  7  8  9 11 13 15 16 17 19 20  0  0  0  0  0  0  0  0]
 [ 1  2  3  4  6  8  9 11 13 14 15 17 18 19 20  0  0  0  0  0]
 [ 2  4  6  7  8  9 10 11 12 13 14 15 16 18  0  0  0  0  0  0]
 [ 1  2  3  5  6  8  9 10 11 12 13 17 19 20  0  0  0  0  0  0]
 [ 1  2  4  6  8  9 10 11 13 14 15 16 17 19 20  0  0  0  0  0]
 [ 1  2  5  6  8  9 11 12 13 15 17 19  0  0  0  0  0  0  0  0]
 [ 1  2  4  5  6  7  9 10 12 20  0  0  0  0  0  0  0  0  0  0]]

restricted_recalls
[[ 1  2  3  8 11 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  2  3  4  5 10 11 13 15 17 18 19 20  0  0  0  0  0  0  0]
 [ 4  6  7  8  9 11 13 15 16 17 19 20  0  0  0  0  0  0  0  0]
 [ 1  2  3  4  6  8  9 11 13 14 15 17 18 19 20  0  0  0  0  0]
 [ 2  4  6  7  8  9 10 11 12 13 14 15 16 18  0  0  0  0  0  0]
 [ 1  2  3  5  6  8  9 10 11 12 13 17 19 20  0  0  0  0  0  0]
 [ 1  2  4  6  8  9 10 11 13 14 15 16 17 19 20  0  0  0  0  0]
 [ 1  2  5  6  8  9 11 12 13 15 17 19  0  0  0  0  0  0  0  0]
 [ 1  2  4  5  6  7  9 10 12 20  0  0  0  0  0  0  0  0  0  0]]

rec_itemids
[[465 514 464 459  67 466   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [ 44 439 441 475 506 442 510  68   7 516   8  12 438   0   0   0   0   0
    0   0]
 [560 559  52 491  65 473 550 492 494  62 489   3   0   0   0   0   0   0
    0   0]
 [500  54 562 503 548  50  64 499  60  63 498 567 564 497  55   0   0   0
    0   0]
 [ 42 528 540 520  26  73 448 530 529 444 451 447   2 450   0   0   0   0
    0   0]
 [ 48  46  29 480  31  38 471 521 535  74 472 468 538 522   0   0   0   0
    0   0]
 [ 76 546  33  40 525  13 482 456  17 483 524 543 484  16  30   0   0   0
    0   0]
 [477 478 474  59  80 547 470 479  56 561 549  57   0   0   0   0   0   0
    0   0]
 [ 41 501 531 476 536 504 534 537  43  37   0   0   0   0   0   0   0   0
    0   0]]

EarlyLPP
[[-3.95610000e+00  6.62420000e-01 -5.63510000e-01  7.20710000e-01
  -6.42350000e-01  4.59200000e-01 -4.62430000e+00 -2.31810000e+00
   1.60860000e+00 -2.30440000e-01 -6.45210945e-01 -1.88230000e-02
   1.75000000e+00 -1.03390000e+00 -2.81790000e-01 -1.10460000e-01
   5.64220000e-01 -3.00120000e+00  5.26260000e-03 -2.05100000e+00]
 [-2.98940000e+00 -1.53130000e+00 -2.80080000e+00  1.16350000e+00
   6.31710000e-01 -1.96410000e+00  4.07130000e+00 -1.45010000e+00
  -9.16470000e-01 -1.14620000e+00 -1.91110000e+00  2.25530000e+00
  -6.69361667e-01  9.51750000e+00 -7.89660000e-01  2.00270000e-01
  -1.68610000e+00 -1.12210000e+00 -1.84050000e-01  1.21510000e+00]
 [ 1.18530000e+00  8.81595000e-01 -3.79755833e-01  1.72370000e-01
  -5.90810000e-01 -1.92500000e+00 -3.38300000e+00  3.62350000e-01
  -1.19340000e+00 -7.18780000e-01  3.31740000e+00  3.91670000e+00
   1.31430000e+00 -2.18210000e+00  3.39510000e+00 -4.04040000e+00
   2.48760000e-01  4.48510000e-01  2.97390000e+00 -2.56870000e+00]
 [ 1.31560000e+00 -2.23890000e+00  1.08790000e-01  2.12720000e+00
   2.49520000e-01  4.76130000e-01  2.49520000e-01  1.01240000e+00
   1.31000000e+00  2.86930000e+00 -1.29430000e+00  7.77760000e-01
  -1.81640000e-01  1.99160000e-01 -2.45090000e-01  3.65740000e+00
   1.03940000e+00 -1.45810000e+00  3.12040000e-01 -3.79970000e+00]
 [ 8.95250000e-01 -4.60290000e-02  3.45220000e-01  1.12960000e+00
   8.77130000e-01 -3.10370000e-01  3.79360000e+00  3.71700000e-02
   8.92955000e-01 -1.70770000e+00  1.84430000e-01  1.45310000e+00
   5.83210000e-01  2.75700000e+00  2.96660000e+00 -2.96070000e+00
  -1.31640000e+00  4.13400000e-01 -1.87190000e+00  1.61990000e+00]
 [ 1.11690000e+00  4.73080000e-02  1.14270000e+00  4.80180000e-01
   1.70810000e+00  9.22820000e-01 -1.94300000e+00  3.31620000e+00
   1.61540000e+00  6.80190000e-01  5.87090000e-01  7.39106667e-01
   2.01140000e-01  6.79472333e-01  1.78710000e-01  7.99090000e-01
  -3.69270000e-01  7.50050000e-01 -1.05540000e+00  2.41010000e+00]
 [ 4.92073077e-01 -1.87190000e+00 -1.17270000e+00  2.19980000e+00
   5.44440000e-01 -3.34450000e-01  1.31090000e+00  1.67420000e+00
   2.38670000e+00 -2.61330000e+00 -2.22560000e+00  3.59090000e+00
  -2.09020000e+00  4.33200000e-01 -1.53650000e-01 -8.24560000e-01
   3.24650000e+00  4.03590000e-01 -3.77670000e-01  3.16380000e+00]
 [-4.44640000e+00 -1.61350000e-01  4.78574889e-01 -5.23230000e-02
  -1.30220000e+00 -5.30810000e-01  4.78574889e-01  4.78574889e-01
   8.42370000e-01  3.66600000e+00 -3.67350000e-01  1.65720000e+00
  -1.87620000e+00 -5.66130000e-02 -1.36930000e+00  1.52890000e+00
   6.70950000e-01  4.78574889e-01  3.01310000e+00  2.40410000e+00]
 [ 1.20880000e+00 -1.86240000e+00  1.95310000e+00  5.44530000e-01
  -1.66700000e-01 -1.62330000e+00  1.49220000e+00  4.94990000e-02
  -1.03760000e-01  3.64560000e-01  4.94990000e-02 -8.81340000e-01
  -1.64640000e-01 -1.26160000e+00  9.72920000e-01 -1.92370000e+00
   4.94990000e-02 -1.98570000e-01  2.12180000e+00 -1.36690000e+00]]

LateLPP
[[-1.8403     -0.23096    -0.30037     0.91095     0.5112      0.92493
   5.469       0.73814     1.6848     -4.3718      0.06368091  1.4111
  -0.58144    -1.3471     -1.8238      0.31522     0.96377    -2.4013
   0.87442    -3.0868    ]
 [-3.2948     -4.1626     -3.3067      1.055       4.6349     -2.1548
   1.6179     -2.4116     -0.91788    -2.263      -1.2416      1.9552
  -1.04278     4.8191     -2.5677      1.9973     -0.16835     0.6839
  -1.0947      3.3385    ]
 [ 1.0006      0.74393667 -0.30081083 -0.44838    -0.75107    -2.4525
  -4.6358      1.6066     -0.5878      0.38968     0.93594     4.0224
   1.1514     -0.95152     3.6602     -4.0981     -0.30656     1.9099
   1.9693     -1.5604    ]
 [ 1.6759     -2.3048      0.076236    0.36634     0.25680742  1.7561
   0.25680742  0.76058     2.2377      3.5446      1.3508      3.2647
  -0.62119    -0.26748     0.72065     3.3244      0.41957     0.057873
   2.6075     -5.9019    ]
 [ 0.13294    -0.26079     2.1002      0.035657    0.8125     -1.034
   7.7875      0.71406     1.83672167 -0.84971     0.14229     1.7396
   2.6421      5.1921      0.32984    -2.2004     -1.8333      1.6058
  -1.6971     -4.1587    ]
 [ 0.98919    -0.90785     0.89095     0.95959     2.7275     -0.1655
  -1.4513      3.3864      2.1181     -2.8027      1.6507      1.25715133
  -0.088492    0.42595     0.50911     1.2835      0.54271     2.1966
  -1.0015      1.8173    ]
 [ 0.47356538 -3.0313     -2.3425      3.2159      0.64089     2.6505
   2.9602      0.94795     1.5985     -0.83089    -3.3718      4.0923
  -1.0686      0.74307    -0.32319    -3.8126      0.87315     1.3315
  -1.2404      4.7862    ]
 [-3.6214      0.13195     0.98048267  1.6644     -0.62942    -0.82545
   0.98048267  0.98048267  1.0433      2.0831      1.2182      2.0362
   0.069894    1.7469     -0.808       0.27846     1.4274      0.98048267
   2.4228      7.6979    ]
 [ 2.4438     -3.413       2.2022     -1.7141      2.2411     -2.8201
  -0.51646    -0.39664     1.0035      2.1985     -0.39664    -0.41565
   0.61412    -2.778      -0.84141    -1.8373     -0.39664    -0.17238167
   0.25061    -1.6185    ]]

condition
[[1 2 1 1 2 2 2 1 2 2 2 2 1 2 2 1 1 2 2 1]
 [2 1 1 1 2 2 2 2 1 1 2 2 1 2 2 2 2 2 2 1]
 [2 1 2 2 2 2 2 1 2 1 1 2 2 2 1 1 2 2 1 2]
 [1 2 2 1 2 2 2 2 2 2 1 1 2 2 1 2 2 2 1 2]
 [2 2 1 2 2 2 2 2 1 1 2 2 1 1 1 2 2 1 2 2]
 [2 2 2 1 1 2 2 2 1 2 2 1 1 2 2 1 1 2 2 2]
 [2 2 2 2 2 1 2 2 1 1 1 2 2 1 2 2 1 2 2 2]
 [1 1 2 2 1 2 2 2 2 2 1 1 2 2 2 1 2 2 2 1]
 [2 1 1 2 1 2 2 2 2 2 2 2 1 2 1 1 2 1 2 2]]

cond3
[[1 2 1 1 3 3 3 1 2 3 2 3 1 3 2 1 1 3 2 1]
 [3 1 1 1 2 3 3 2 1 1 2 2 1 2 3 3 2 3 3 1]
 [3 1 2 2 2 2 3 1 3 1 1 2 2 3 1 1 3 2 1 3]
 [1 3 2 1 2 2 3 3 3 2 1 1 3 3 1 2 2 2 1 3]
 [3 3 1 2 2 2 2 3 1 1 2 2 1 1 1 3 3 1 2 3]
 [3 3 3 1 1 3 2 3 1 2 2 1 1 3 2 1 1 2 2 2]
 [2 2 3 2 3 1 2 3 1 1 1 3 3 1 2 2 1 3 3 3]
 [1 1 3 2 1 3 2 3 2 2 1 1 3 3 2 1 2 2 3 1]
 [3 1 1 2 1 2 2 3 2 2 2 3 1 2 1 1 3 1 3 3]]

lpp_imputed
[[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0]]

In [16]:
talmi_metadata

{'item_categories': ['cat1',
  'cat10',
  'cat102',
  'cat103',
  'cat104',
  'cat105',
  'cat106',
  'cat107',
  'cat110',
  'cat112',
  'cat114',
  'cat115',
  'cat116',
  'cat117',
  'cat12',
  'cat120',
  'cat122',
  'cat124',
  'cat126',
  'cat128',
  'cat129',
  'cat13',
  'cat130',
  'cat133',
  'cat135',
  'cat138',
  'cat141',
  'cat143',
  'cat145',
  'cat146',
  'cat147',
  'cat149',
  'cat15',
  'cat16',
  'cat17',
  'cat21',
  'cat22',
  'cat24',
  'cat27',
  'cat28',
  'cat33',
  'cat4',
  'cat41',
  'cat43',
  'cat44',
  'cat46',
  'cat47',
  'cat49',
  'cat51',
  'cat52',
  'cat54',
  'cat59',
  'cat62',
  'cat66',
  'cat70',
  'cat73',
  'cat8',
  'cat86',
  'cat88',
  'cat89',
  'cat9',
  'cat92',
  'cat93',
  'cat94',
  'cat95',
  'cat98',
  'missing_202_1_11',
  'missing_202_2_13',
  'missing_202_3_2',
  'missing_202_3_3',
  'missing_202_4_5',
  'missing_202_4_7',
  'missing_202_5_9',
  'missing_202_6_12',
  'missing_202_6_14',
  'missing_202_7_1',
  'missing_202_8_18',
  'missing_202_8_3',
  'missing_202_8_7',
  'missing_202_8_8',
  'missing_202_9_11',
  'missing_202_9_17',
  'missing_202_9_18',
  'missing_202_9_8',
  'missing_203_3_10',
  'missing_203_5_18',
  'missing_203_5_20',
  'missing_203_7_1',
  'missing_203_7_15',
  'missing_203_7_6',
  'missing_203_9_12',
  'missing_204_2_10',
  'missing_204_2_8',
  'missing_204_3_12',
  'missing_204_3_13',
  'missing_204_5_20',
  'missing_204_6_2',
  'missing_204_7_1',
  'missing_204_7_20',
  'missing_204_8_20',
  'missing_204_8_3',
  'missing_204_8_6',
  'missing_204_9_15',
  'missing_204_9_19',
  'missing_204_9_2',
  'missing_204_9_9',
  'missing_205_1_1',
  'missing_205_1_3',
  'missing_205_2_12',
  'missing_205_5_16',
  'missing_205_7_1',
  'missing_205_8_1',
  'missing_205_8_2',
  'missing_205_8_3',
  'missing_205_9_11',
  'missing_206_2_11',
  'missing_206_3_3',
  'missing_206_4_15',
  'missing_206_4_19',
  'missing_206_4_4',
  'missing_206_4_9',
  'missing_206_7_1',
  'missing_206_8_18',
  'missing_206_8_6',
  'missing_206_9_16',
  'missing_206_9_20',
  'missing_207_1_11',
  'missing_207_2_12',
  'missing_207_3_6',
  'missing_207_4_11',
  'missing_207_5_7',
  'missing_207_7_1',
  'missing_207_7_11',
  'missing_207_7_17',
  'missing_207_8_12',
  'missing_207_8_15',
  'missing_207_8_19',
  'missing_210_1_20',
  'missing_210_7_1',
  'missing_210_8_18',
  'missing_211_3_19',
  'missing_211_3_20',
  'missing_211_4_15',
  'missing_211_4_8',
  'missing_211_5_20',
  'missing_211_7_1',
  'missing_212_2_12',
  'missing_212_2_7',
  'missing_212_5_1',
  'missing_212_5_2',
  'missing_212_5_3',
  'missing_212_5_4',
  'missing_212_6_20',
  'missing_212_6_8',
  'missing_212_6_9',
  'missing_212_7_1',
  'missing_213_1_10',
  'missing_213_1_16',
  'missing_213_2_13',
  'missing_213_2_5',
  'missing_213_2_8',
  'missing_213_3_4',
  'missing_213_4_14',
  'missing_213_6_3',
  'missing_213_7_1',
  'missing_213_7_4',
  'missing_213_8_11',
  'missing_213_8_19',
  'missing_213_8_8',
  'missing_213_9_12',
  'missing_213_9_13',
  'missing_213_9_14',
  'missing_213_9_17',
  'missing_213_9_8',
  'missing_214_2_8',
  'missing_214_5_19',
  'missing_214_5_7',
  'missing_214_6_20',
  'missing_214_6_9',
  'missing_214_7_1',
  'missing_214_7_13',
  'missing_214_8_19',
  'missing_214_9_11',
  'missing_214_9_12',
  'missing_214_9_19',
  'missing_215_1_4',
  'missing_215_2_4',
  'missing_215_2_6',
  'missing_215_4_20',
  'missing_215_4_5',
  'missing_215_5_9',
  'missing_215_6_18',
  'missing_215_6_5',
  'missing_215_7_1',
  'missing_215_8_6',
  'missing_215_8_7',
  'missing_215_9_1',
  'missing_215_9_7',
  'missing_216_1_4',
  'missing_216_2_12',
  'missing_216_2_19',
  'missing_216_6_3',
  'missing_216_6_8',
  'missing_216_7_1',
  'missing_216_7_20',
  'missing_217_1_15',
  'missing_217_1_4',
  'missing_217_4_1',
  'missing_217_4_16',
  'missing_217_4_18',
  'missing_217_5_17',
  'missing_217_6_14',
  'missing_217_6_18',
  'missing_217_7_1',
  'missing_217_7_20',
  'missing_217_7_9',
  'missing_217_8_4',
  'missing_217_9_8',
  'missing_217_9_9',
  'missing_218_3_14',
  'missing_218_7_1',
  'missing_219_1_13',
  'missing_219_2_2',
  'missing_219_3_1',
  'missing_219_3_16',
  'missing_219_4_11',
  'missing_219_7_1',
  'missing_219_8_3',
  'missing_219_9_17',
  'missing_220_1_14',
  'missing_220_7_1',
  'missing_220_7_16',
  'missing_220_8_2',
  'missing_220_8_7',
  'missing_220_9_12',
  'missing_221_1_15',
  'missing_221_1_16',
  'missing_221_1_17',
  'missing_221_1_18',
  'missing_221_1_5',
  'missing_221_7_1',
  'missing_221_7_18',
  'missing_222_4_20',
  'missing_222_5_19',
  'missing_222_7_1',
  'missing_222_7_10',
  'missing_222_7_11',
  'missing_222_7_9',
  'missing_223_3_19',
  'missing_223_3_20',
  'missing_223_4_18',
  'missing_223_4_5',
  'missing_223_4_6',
  'missing_223_6_17',
  'missing_223_6_18',
  'missing_223_7_1',
  'missing_223_7_4',
  'missing_223_8_1',
  'missing_223_8_2',
  'missing_223_8_20',
  'missing_223_8_3',
  'missing_223_8_8',
  'missing_223_9_9',
  'missing_224_3_10',
  'missing_224_3_2',
  'missing_224_5_1',
  'missing_224_5_11',
  'missing_224_5_12',
  'missing_224_5_3',
  'missing_224_5_4',
  'missing_224_5_5',
  'missing_224_7_1',
  'missing_224_9_8',
  'missing_225_1_13',
  'missing_225_1_5',
  'missing_225_1_9',
  'missing_225_2_12',
  'missing_225_2_15',
  'missing_225_3_18',
  'missing_225_5_3',
  'missing_225_5_5',
  'missing_225_5_9',
  'missing_225_7_1',
  'missing_225_9_8',
  'missing_226_1_20',
  'missing_226_2_6',
  'missing_226_3_1',
  'missing_226_5_19',
  'missing_226_5_7',
  'missing_226_6_11',
  'missing_226_6_16',
  'missing_226_6_3',
  'missing_226_7_1',
  'missing_226_9_3',
  'missing_227_7_1',
  'missing_227_7_2',
  'missing_229_1_15',
  'missing_229_1_6',
  'missing_229_2_19',
  'missing_229_3_1',
  'missing_229_3_11',
  'missing_229_4_11',
  'missing_229_7_1',
  'missing_229_8_10',
  'missing_229_8_17',
  'missing_229_8_3',
  'missing_229_8_9',
  'missing_229_9_3',
  'missing_230_2_4',
  'missing_230_3_11',
  'missing_230_3_13',
  'missing_230_3_14',
  'missing_230_3_4',
  'missing_230_4_12',
  'missing_230_4_16',
  'missing_230_4_6',
  'missing_230_5_1',
  'missing_230_5_12',
  'missing_230_5_15',
  'missing_230_5_17',
  'missing_230_5_5',
  'missing_230_7_1',
  'missing_230_7_19',
  'missing_230_7_2',
  'missing_230_7_4',
  'missing_230_9_18',
  'missing_230_9_2',
  'missing_231_3_1',
  'missing_231_3_3',
  'missing_231_3_4',
  'missing_231_4_18',
  'missing_231_4_19',
  'missing_231_4_9',
  'missing_231_5_11',
  'missing_231_5_6',
  'missing_231_7_1',
  'missing_231_9_1',
  'missing_231_9_19',
  'missing_232_1_19',
  'missing_232_2_7',
  'missing_232_6_12',
  'missing_232_7_1',
  'missing_232_7_19',
  'missing_232_7_8',
  'missing_232_9_20',
  'missing_233_1_11',
  'missing_233_1_7',
  'missing_233_3_11',
  'missing_233_3_3',
  'missing_233_5_8',
  'missing_233_5_9',
  'missing_233_6_19',
  'missing_233_7_1',
  'missing_233_7_12',
  'missing_233_7_7',
  'missing_233_8_16',
  'missing_233_8_7',
  'missing_233_9_16',
  'missing_234_1_19',
  'missing_234_3_12',
  'missing_234_7_1',
  'missing_234_7_13',
  'missing_234_8_14',
  'missing_234_9_3',
  'missing_234_9_4',
  'missing_235_1_1',
  'missing_235_5_3',
  'missing_235_7_1',
  'missing_235_9_10',
  'missing_235_9_2',
  'missing_236_1_17',
  'missing_236_1_6',
  'missing_236_4_19',
  'missing_236_4_2',
  'missing_236_7_1',
  'missing_236_7_17',
  'missing_236_7_5',
  'missing_236_8_20',
  'missing_237_1_14',
  'missing_237_5_8',
  'missing_237_7_1',
  'missing_237_7_6',
  'missing_237_8_15',
  'missing_237_8_20',
  'missing_237_9_15',
  'missing_237_9_7',
  'missing_237_9_8',
  'missing_238_4_11',
  'missing_238_7_1',
  'missing_238_7_6',
  'missing_238_8_6',
  'missing_238_8_7',
  'missing_238_9_12',
  'missing_239_1_19',
  'missing_239_1_20',
  'missing_239_2_2',
  'missing_239_2_20',
  'missing_239_3_11',
  'missing_239_3_13',
  'missing_239_3_16',
  'missing_239_4_15',
  'missing_239_4_2',
  'missing_239_4_6',
  'missing_239_6_11',
  'missing_239_7_1',
  'missing_239_7_6',
  'missing_239_8_3',
  'missing_239_8_4',
  'missing_239_9_19',
  'missing_239_9_20',
  'missing_240_3_17',
  'missing_240_3_20',
  'missing_240_3_3',
  'missing_240_6_10',
  'missing_240_6_11',
  'missing_240_6_9',
  'missing_240_7_1',
  'missing_240_8_11',
  'missing_241_1_16',
  'missing_241_2_10',
  'missing_241_2_15',
  'missing_241_4_17',
  'missing_241_4_18',
  'missing_241_7_1',
  'missing_241_9_15',
  'missing_241_9_3',
  'missing_241_9_7',
  'missing_242_1_1',
  'missing_242_1_9',
  'missing_242_2_20',
  'missing_242_3_12',
  'missing_242_3_20',
  'missing_242_4_12',
  'missing_242_6_7',
  'missing_242_7_1',
  'missing_242_8_6',
  'missing_242_9_7',
  'neg102',
  'neg104',
  'neg109',
  'neg110',
  'neg111',
  'neg112',
  'neg113',
  'neg114',
  'neg115',
  'neg117',
  'neg118',
  'neg12',
  'neg120',
  'neg121',
  'neg122',
  'neg123',
  'neg124',
  'neg126',
  'neg127',
  'neg128',
  'neg129',
  'neg130',
  'neg131',
  'neg132',
  'neg134',
  'neg137',
  'neg138',
  'neg139',
  'neg14',
  'neg140',
  'neg141',
  'neg143',
  'neg144',
  'neg145',
  'neg146',
  'neg150',
  'neg2',
  'neg20',
  'neg24',
  'neg28',
  'neg3',
  'neg30',
  'neg35',
  'neg37',
  'neg39',
  'neg40',
  'neg43',
  'neg46',
  'neg49',
  'neg55',
  'neg57',
  'neg6',
  'neg60',
  'neg63',
  'neg64',
  'neg65',
  'neg69',
  'neg8',
  'neg80',
  'neg83',
  'neg84',
  'neg90',
  'neg92',
  'neg96',
  'neg98',
  'neg99',
  'neut1',
  'neut100',
  'neut11',
  'neut13',
  'neut14',
  'neut15',
  'neut16',
  'neut17',
  'neut18',
  'neut19',
  'neut2',
  'neut21',
  'neut22',
  'neut23',
  'neut25',
  'neut26',
  'neut27',
  'neut28',
  'neut29',
  'neut3',
  'neut30',
  'neut31',
  'neut32',
  'neut33',
  'neut34',
  'neut36',
  'neut37',
  'neut38',
  'neut39',
  'neut4',
  'neut40',
  'neut41',
  'neut42',
  'neut43',
  'neut44',
  'neut45',
  'neut46',
  'neut48',
  'neut49',
  'neut50',
  'neut51',
  'neut58',
  'neut59',
  'neut6',
  'neut62',
  'neut63',
  'neut69',
  'neut7',
  'neut71',
  'neut74',
  'neut75',
  'neut77',
  'neut79',
  'neut8',
  'neut80',
  'neut84',
  'neut87',
  'neut88',
  'neut89',
  'neut9',
  'neut90',
  'neut91',
  'neut93',
  'neut95',
  'neut97',
  'neut98'],
 'condition_categories': ['Negative', 'Neutral'],
 'cond3_categories': ['Negative', 'Neutral', 'Category']}